export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const LOAD_ARTICLE_IDS_REQUEST = 'LOAD_ARTICLE_IDS_REQUEST';
export const LOAD_ARTICLE_IDS_SUCCESS = 'LOAD_ARTICLE_IDS_SUCCESS';
export const LOAD_ARTICLE_IDS_FAILURE = 'LOAD_ARTICLE_IDS_FAILURE';

export const LOAD_VIDEO_IDS_REQUEST = 'LOAD_VIDEO_IDS_REQUEST';
export const LOAD_VIDEO_IDS_SUCCESS = 'LOAD_VIDEO_IDS_SUCCESS';
export const LOAD_VIDEO_IDS_FAILURE = 'LOAD_VIDEO_IDS_FAILURE';

export const LOAD_VIDEOS_REQUEST = 'LOAD_VIDEOS_REQUEST';
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_VIDEOS_FAILURE = 'LOAD_VIDEOS_FAILURE';

export const LOAD_TAGS_REQUEST = 'LOAD_TAGS_REQUEST';
export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';

export const LOAD_EVENT_IDS_REQUEST = 'LOAD_EVENT_IDS_REQUEST';
export const LOAD_EVENT_IDS_SUCCESS = 'LOAD_EVENT_IDS_SUCCESS';
export const LOAD_EVENT_IDS_FAILURE = 'LOAD_EVENT_IDS_FAILURE';

export const LOAD_EVENT_REQUEST = 'LOAD_EVENT_REQUEST';
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS';
export const LOAD_EVENT_FAILURE = 'LOAD_EVENT_FAILURE';

export const LOAD_MAIN_EVENT_REQUEST = 'LOAD_MAIN_EVENT_REQUEST';
export const LOAD_MAIN_EVENT_SUCCESS = 'LOAD_MAIN_EVENT_SUCCESS';
export const LOAD_MAIN_EVENT_FAILURE = 'LOAD_MAIN_EVENT_FAILURE';

export const LOAD_FEATURED_EVENTS_REQUEST = 'LOAD_FEATURED_EVENTS_REQUEST';
export const LOAD_FEATURED_EVENTS_SUCCESS = 'LOAD_FEATURED_EVENTS_SUCCESS';
export const LOAD_FEATURED_EVENTS_FAILURE = 'LOAD_FEATURED_EVENTS_FAILURE';