export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const LOAD_ARTICLE_IDS_REQUEST = 'LOAD_ARTICLE_IDS_REQUEST';
export const LOAD_ARTICLE_IDS_SUCCESS = 'LOAD_ARTICLE_IDS_SUCCESS';
export const LOAD_ARTICLE_IDS_FAILURE = 'LOAD_ARTICLE_IDS_FAILURE';