export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const LOAD_ARTICLE_IDS_REQUEST = 'LOAD_ARTICLE_IDS_REQUEST';
export const LOAD_ARTICLE_IDS_SUCCESS = 'LOAD_ARTICLE_IDS_SUCCESS';
export const LOAD_ARTICLE_IDS_FAILURE = 'LOAD_ARTICLE_IDS_FAILURE';

export const LOAD_VIDEO_IDS_REQUEST = 'LOAD_VIDEO_IDS_REQUEST';
export const LOAD_VIDEO_IDS_SUCCESS = 'LOAD_VIDEO_IDS_SUCCESS';
export const LOAD_VIDEO_IDS_FAILURE = 'LOAD_VIDEO_IDS_FAILURE';

export const LOAD_VIDEOS_REQUEST = 'LOAD_VIDEOS_REQUEST';
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_VIDEOS_FAILURE = 'LOAD_VIDEOS_FAILURE';

export const LOAD_TAGS_REQUEST = 'LOAD_TAGS_REQUEST';
export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';